### ISSUE TITLE
Opengl throwing invalid operation after using "with query:"

### ISSUE THREAD

**Issue by Rafale25** [moderngl/moderngl#552]
Opengl is throwing an invalid operation after using a "with query:"

ModernGL version is 5.7.4

query is created with `ctx.query()`

The error is raised after the second time query() is used.

```
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glMemoryBarrier,
        cArguments = (GL_SHADER_STORAGE_BARRIER_BIT,)
)
```

**Comment by einarf** [comment]
It happens the second time you enter/exit the query
```py
with query:
    # stuff
```

**Comment by szabolcsdombi** [comment]
it should not be re-entrant, we should raise an Exception and make it clear.

**Comment by szabolcsdombi** [comment]
This should fix it: https://github.com/moderngl/moderngl/commit/9588c504d743ed95c58ea7fb9581d0d10d077cea

needs more testing before release.

**Comment by Rafale25** [comment]
I just tried the fix and it didn't fix the error.
But I noticed that the error is also triggered when just accessing `query.elapsed` without using `with query:` at all.

**Comment by szabolcsdombi** [comment]
We are using `glGetQueryObjectiv` but we should use `glGetQueryObjectuiv` for `QUERY_RESULT` (ref: [glspec46](https://registry.khronos.org/OpenGL/specs/gl/glspec46.core.pdf)).

The other problem is that we assumed the default 0 value will be returned for not yet executed queries. (ref: [khronos registry](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetQueryObject.xhtml))
I expect the reason accessing `query.elapsed` without using `with query:` generates an OpenGL error due to the wait time is undefined/infinite, but in that case "The initial value is 0." is misleading.

**Comment by szabolcsdombi** [comment]
also `query.elapsed` should only be accessed if the Query was created with the `time_elapsed` flag set.

**Comment by szabolcsdombi** [comment]
https://github.com/moderngl/moderngl/commit/4fab9bd2d0713090bfdd5a24116e566923e8fc18

**Comment by szabolcsdombi** [comment]
is this working with the fix above?

**Comment by Rafale25** [comment]
Nope :(, same error.

**Comment by Rafale25** [comment]
I made a minimal working example of the bug to make it easier for you tu debug

```py
from OpenGL import GL
import moderngl
import moderngl_window
from moderngl_window.opengl.vao import VAO

vertex_shader = \
'''
#version 330 core

void main() {
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
}
'''

fragment_shader = \
'''
#version 330 core

out vec4 frag_color;

void main() {
    frag_color = vec4(1.0, 1.0, 1.0, 1.0);
}

'''

class Test(moderngl_window.WindowConfig):
    gl_version = (3, 3)
    window_size = (400, 400)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.query = self.ctx.query(time=True)

        self.program = self.ctx.program(
            vertex_shader=vertex_shader,
            fragment_shader=fragment_shader
        )

        self.vao = VAO(mode=moderngl.POINTS)

    def render(self, time, frametime):
        with self.query:
            self.vao.render(program=self.program, vertices=1)

        GL.glMemoryBarrier(GL.GL_SHADER_STORAGE_BARRIER_BIT)

if __name__ == '__main__':
    Test.run()
```

**Comment by szabolcsdombi** [comment]
the example above invokes any sample passed and similar despite it should only run the time related query.
it was due to a dirty read from the uninitialized slots for the other query types.
fixed in https://github.com/moderngl/moderngl/commit/3413e64aefd46728a63462293c51848ad6472e1a

**Comment by Rafale25** [comment]
Thank you !! It's working, i'm closing the issue
